package com.langqu.httpdemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.langqu.httpdemo.greendao.TestDaoBean;

import com.langqu.httpdemo.greendao.TestDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDaoBeanDaoConfig;

    private final TestDaoBeanDao testDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDaoBeanDaoConfig = daoConfigMap.get(TestDaoBeanDao.class).clone();
        testDaoBeanDaoConfig.initIdentityScope(type);

        testDaoBeanDao = new TestDaoBeanDao(testDaoBeanDaoConfig, this);

        registerDao(TestDaoBean.class, testDaoBeanDao);
    }
    
    public void clear() {
        testDaoBeanDaoConfig.clearIdentityScope();
    }

    public TestDaoBeanDao getTestDaoBeanDao() {
        return testDaoBeanDao;
    }

}
